### ISSUE TITLE
GitHub Actionsで自動テスト環境を整える

### ISSUE THREAD

**Issue by kotamanegi** [kusumotolab/pycasl2-pycomet2-java#8]
## 概要
このリポジトリには自動テスト環境が整備されておらず、テストを通過していないコードをマージしてしまう可能性があります。
GitHubが提供しているGitHub Actionsを使って自動テスト環境を整備したいです。

## タスク

- [x] GitHub Actions上でJavaの実行環境を整える
- [x] GitHub Actions上でテストを実行する
- [x] 動作検証 (以下の3つを確認)
  - 正常にテストが通過する例
  - テスト途中で失敗する例
  - ビルドに失敗する例

## 技術選定の根拠
主流な自動テストツールとしてGitHub ActionsとTravisとJenkinsの3つがあります。
- GitHub Actions
  - 利点
    - GitHubと密に連携しており、開発フローの構築に使いやすい
    - 自前のサーバーを用意しなくともGitHub側が用意してくれる
    - 動作環境がある程度整備されており、すぐに使い始めることができる
  - 欠点
    - GitHub外では使えない
    - 月2000時間の無料枠を超えると課金するまで使えなくなる
      -  このリポジトリでは問題点になりづらい 
- Travis
  - 利点
    - 設定ファイルが既に作成されているので、環境を整えるだけで使える
  -  欠点
     -  外部サービスであるため、GitHubとの連携性が悪い    
- Jenkins
  - 利点
    -  情報科学演習Dでも用いられており、ノウハウが既に蓄積されている
    -  自前のサーバーで使用することができる
  - 欠点
    -  自前のサーバーを用意する必要がある
    -  セットアップが比較的面倒

私はGitHub Actionsの方が利点が大きいと感じるので、GitHub Actionsを使う実装を採用したいです。

**Comment by hrtwt** [comment]
> 自動テスト環境が整備されておらず

Travisでやっている気がしています．

例えば，前回のテスト
https://github.com/kusumotolab/jcasl2-jcomet2/runs/4723097898
https://app.travis-ci.com/github/kusumotolab/jcasl2-jcomet2/builds/244366950

なので，このissueはTravisからGitHub Actionsに乗り換える意図と読み替えてもいいですか．
ghaのほうが使い勝手いいのは同意します．

**Comment by hrtwt** [comment]
> 月2000時間の無料枠を超えると課金するまで使えなくなる

のはprivate repoの制約だったと思います．

本リポジトリはpublicなので問題なし．

**Comment by shinsuke-mat** [comment]
@kotamanegi thx 

GHA移行してよいです．
@hrtwt 内容確認頼む．

補足：
CIは前からtravis使っていたけど，travisがcomからorgに移行したタイミングで死んでた．
ちょっと前にtravis周りのアップデートはした．
![image](https://user-images.githubusercontent.com/5342911/149886576-69a03b11-0f1f-4559-b881-43788d062624.png)

GHAにできるならそっちの方が良い．

**Comment by shinsuke-mat** [comment]
ちなみにgradleラッパーは2022で更新してあるのでそのまま使えるはず
